branch-defaults:
  default:
    environment: sixpack-prd
    group_suffix: null
global:
  application_name: Sixpack
  default_ec2_keyname: prod
  default_platform: 64bit Amazon Linux 2016.03 v2.1.0 running Python 2.7
  default_region: us-east-1
  profile: null
  sc: null
